### PR TITLE
VSCode config + debuggers

### PR DESCRIPTION
**Pull request by DylanTackoor**
Adds:

- Chrome/Firefox debug profiles
- Extension recommendations
- Configures default `SUPER+Shift+B` shortcut to run `npm run build`
- Recommends relevant extensions

### CODE REVIEW

**Comment by RenaudRohlinger** [comment]
Thanks @DylanTackoor this feature is very interesting. I never configured the debugger on Canvas but it looks amazing.

Nevertheless, it seems the configuration breaks the usual usage of VSCode. After pulling your branch I can't save any file anymore and get this message :
image

**Comment by DylanTackoor** [comment]
Ahhhh I'll check it out with a clean vscode install in the morning.

I pulled the debug config from here and added the Firefox profile 😄 https://github.com/microsoft/vscode-recipes/tree/master/Next-js

**Comment by DylanTackoor** [comment]
having trouble reproducing with a clean vscode install :sweat: Whenever you get a chance can you check if you can save after deleting the `settings.json` file? Thinking maybe it's better to just remove it as the debug config is the most helpful part of the PR

**Comment by RenaudRohlinger** [comment]
@DylanTackoor Ok, I tried again and everything seems to work so it should be ok to merge. Could you please update your branch with the main so I can merge?

**Comment by DylanTackoor** [comment]
rebased off main, should be good to go :smile:

**Pull request merged**
